
LOAD DATA 
CHARACTERSET UTF8
INFILE 'spp_custom_error.txt'
INSERT
INTO TABLE SPP_CUSTOM_ERROR
FIELDS TERMINATED BY "|" OPTIONALLY ENCLOSED BY '"' TRAILING NULLCOLS 
( PORTAL, LOCALE, ERROR_CODE, CUSTOM_ERROR_MESSAGE)

