
LOAD DATA 
CHARACTERSET UTF8
INFILE 'spp_login_label.txt'
INSERT
INTO TABLE SPP_LOGIN_LABEL
FIELDS TERMINATED BY "|" OPTIONALLY ENCLOSED BY '"' TRAILING NULLCOLS 
( LOCALE, LABEL, MESSAGE char (1024))

