
LOAD DATA 
CHARACTERSET UTF8
INFILE 'SPP_CONTACT_TOPICS.txt'
REPLACE
INTO TABLE SPP_CONTACT_TOPICS
FIELDS TERMINATED BY "|" OPTIONALLY ENCLOSED BY '"'
( LANGUAGECODE,TOPICCODE,TOPICLABEL,USERID)

