LOAD DATA 
CHARACTERSET UTF8
INFILE 'SPP_CONTACT_FAULTS.txt'
REPLACE
INTO TABLE SPP_CONTACT_FAULTS
FIELDS TERMINATED BY "|" OPTIONALLY ENCLOSED BY '"'
( LANGUAGECODE,RULENUMBER,CODE,FIELDNAME,DESCRIPTION)

