
LOAD DATA 
CHARACTERSET UTF8
INFILE 'SPP_CONTACT_LANGUAGE.txt'
REPLACE
INTO TABLE SPP_CONTACT_LANGUAGE
FIELDS TERMINATED BY "|" OPTIONALLY ENCLOSED BY '"'
( LANGUAGECODE,LANGUAGELABEL,ISHPPCOMPLIANT)

