
-- The DDL (Data Definition Language) statements in this file must be tailored to the target environment.
-- Do this by changing the string '#OWNERID#' to the appropriate schema owner id which should own the objects.
--      >> For CAS Central tables, this is typically in the pattern 'CAS##'.
--      >> For CAS Application Database tables, this is typically in the pattern 'CASAPP##'.




begin execute immediate 'DROP TABLE CAS02.USER_ATTR_VALU CASCADE CONSTRAINTS PURGE'; exception when others then null; end;/



begin execute immediate 'DROP TABLE CAS02.USER_ID_TYPE CASCADE CONSTRAINTS PURGE'; exception when others then null; end;/



begin execute immediate 'DROP TABLE CAS02.APP_USER_ATTR_PRMSN CASCADE CONSTRAINTS PURGE'; exception when others then null; end;/



begin execute immediate 'DROP TABLE CAS02.APP_CMPND_ATTR_SMPL_ATTR_PRMSN CASCADE CONSTRAINTS PURGE'; exception when others then null; end;/



begin execute immediate 'DROP TABLE CAS02.CMPND_ATTR_SMPL_ATTR CASCADE CONSTRAINTS PURGE'; exception when others then null; end;/



begin execute immediate 'DROP TABLE CAS02.USER_ATTR CASCADE CONSTRAINTS PURGE'; exception when others then null; end;/



begin execute immediate 'DROP TABLE CAS02.USER_ATTR_TYPE CASCADE CONSTRAINTS PURGE'; exception when others then null; end;/

commit/

CREATE TABLE CAS02.APP_CMPND_ATTR_SMPL_ATTR_PRMSN
(
	APP_PRTFL_ID          INTEGER  NOT NULL ,
	CMPND_USER_ATTR_ID    VARCHAR2(30)  NOT NULL ,
	SMPL_USER_ATTR_ID     VARCHAR2(30)  NOT NULL ,
	CRT_USER_ID           VARCHAR2(140)   DEFAULT  ' ' NOT NULL ,
	CRT_TS                TIMESTAMP   DEFAULT  SYSTIMESTAMP NOT NULL 
)
	TABLESPACE CASDATA01/



CREATE UNIQUE INDEX CAS02.PK_APP_CMPND_ATTR_SMPL_ATTR_PR ON CAS02.APP_CMPND_ATTR_SMPL_ATTR_PRMSN
(APP_PRTFL_ID  ASC,CMPND_USER_ATTR_ID  ASC,SMPL_USER_ATTR_ID  ASC)
	TABLESPACE CASINDX01/



ALTER TABLE CAS02.APP_CMPND_ATTR_SMPL_ATTR_PRMSN
	ADD CONSTRAINT  PK_APP_CMPND_ATTR_SMPL_ATTR_PR PRIMARY KEY (APP_PRTFL_ID,CMPND_USER_ATTR_ID,SMPL_USER_ATTR_ID)/



CREATE INDEX CAS02.IE1_APP_CMPND_ATTR_SMPL_ATTR_P ON CAS02.APP_CMPND_ATTR_SMPL_ATTR_PRMSN
(CMPND_USER_ATTR_ID  ASC,SMPL_USER_ATTR_ID  ASC)
	TABLESPACE CASINDX01/



CREATE TABLE CAS02.APP_USER_ATTR_PRMSN
(
	APP_PRTFL_ID          INTEGER  NOT NULL ,
	USER_ATTR_ID          VARCHAR2(30)  NOT NULL ,
	CRT_USER_ID           VARCHAR2(140)   DEFAULT  ' ' NOT NULL ,
	CRT_TS                TIMESTAMP   DEFAULT  SYSTIMESTAMP NOT NULL 
)
	TABLESPACE CASDATA01/



CREATE UNIQUE INDEX CAS02.PK_APP_USER_ATTR_PRMSN ON CAS02.APP_USER_ATTR_PRMSN
(APP_PRTFL_ID  ASC,USER_ATTR_ID  ASC)
	TABLESPACE CASINDX01/



ALTER TABLE CAS02.APP_USER_ATTR_PRMSN
	ADD CONSTRAINT  PK_APP_USER_ATTR_PRMSN PRIMARY KEY (APP_PRTFL_ID,USER_ATTR_ID)/



CREATE INDEX CAS02.IE1_APP_USER_ATTR_PRMSN ON CAS02.APP_USER_ATTR_PRMSN
(USER_ATTR_ID  ASC)
	TABLESPACE CASINDX01/



CREATE TABLE CAS02.CMPND_ATTR_SMPL_ATTR
(
	CMPND_USER_ATTR_ID    VARCHAR2(30)  NOT NULL ,
	SMPL_USER_ATTR_ID     VARCHAR2(30)  NOT NULL ,
	CRT_USER_ID           VARCHAR2(140)   DEFAULT  ' ' NOT NULL ,
	CRT_TS                TIMESTAMP   DEFAULT  SYSTIMESTAMP NOT NULL 
)
	TABLESPACE CASDATA01/



CREATE UNIQUE INDEX CAS02.PK_CMPND_ATTR_SMPL_ATTR ON CAS02.CMPND_ATTR_SMPL_ATTR
(CMPND_USER_ATTR_ID  ASC,SMPL_USER_ATTR_ID  ASC)
	TABLESPACE CASINDX01/



ALTER TABLE CAS02.CMPND_ATTR_SMPL_ATTR
	ADD CONSTRAINT  PK_CMPND_ATTR_SMPL_ATTR PRIMARY KEY (CMPND_USER_ATTR_ID,SMPL_USER_ATTR_ID)/



CREATE INDEX CAS02.IE1_CMPND_ATTR_SMPL_ATTR ON CAS02.CMPND_ATTR_SMPL_ATTR
(SMPL_USER_ATTR_ID  ASC)
	TABLESPACE CASINDX01/



CREATE TABLE CAS02.USER_ATTR
(
	USER_ATTR_ID          VARCHAR2(30)  NOT NULL ,
	CRT_USER_ID           VARCHAR2(140)   DEFAULT  ' ' NOT NULL ,
	CRT_TS                TIMESTAMP   DEFAULT  SYSTIMESTAMP NOT NULL ,
	LAST_MAINT_USER_ID    VARCHAR2(140)   DEFAULT  ' ' NOT NULL ,
	LAST_MAINT_TS         TIMESTAMP   DEFAULT  SYSTIMESTAMP NOT NULL ,
	USER_ATTR_TYPE_CD     VARCHAR2(10)   DEFAULT  ' ' NOT NULL ,
	USER_ATTR_NM          VARCHAR2(60)   DEFAULT  ' ' NOT NULL ,
	USER_ATTR_DN          VARCHAR2(255)   DEFAULT  ' ' NOT NULL ,
	USER_ATTR_DEFN_TX     CLOB   DEFAULT  EMPTY_CLOB() NOT NULL 
)
	TABLESPACE CASDATA01/



CREATE UNIQUE INDEX CAS02.PK_USER_ATTR ON CAS02.USER_ATTR
(USER_ATTR_ID  ASC)
	TABLESPACE CASINDX01/



ALTER TABLE CAS02.USER_ATTR
	ADD CONSTRAINT  PK_USER_ATTR PRIMARY KEY (USER_ATTR_ID)/



CREATE UNIQUE INDEX CAS02.AK1_USER_ATTR ON CAS02.USER_ATTR
(USER_ATTR_NM  ASC)
	TABLESPACE CASINDX01/



CREATE INDEX CAS02.IE1_USER_ATTR ON CAS02.USER_ATTR
(USER_ATTR_TYPE_CD  ASC)
	TABLESPACE CASINDX01/



CREATE TABLE CAS02.USER_ATTR_TYPE
(
	USER_ATTR_TYPE_CD     VARCHAR2(10)  NOT NULL ,
	CRT_USER_ID           VARCHAR2(140)   DEFAULT  ' ' NOT NULL ,
	CRT_TS                TIMESTAMP   DEFAULT  SYSTIMESTAMP NOT NULL ,
	LAST_MAINT_USER_ID    VARCHAR2(140)   DEFAULT  ' ' NOT NULL ,
	LAST_MAINT_TS         TIMESTAMP   DEFAULT  SYSTIMESTAMP NOT NULL ,
	USER_ATTR_TYPE_NM     VARCHAR2(60)   DEFAULT  ' ' NOT NULL ,
	USER_ATTR_TYPE_DN     VARCHAR2(255)   DEFAULT  ' ' NOT NULL 
)
	TABLESPACE CASDATA01/



CREATE UNIQUE INDEX CAS02.PK_USER_ATTR_TYPE ON CAS02.USER_ATTR_TYPE
(USER_ATTR_TYPE_CD  ASC)
	TABLESPACE CASINDX01/



ALTER TABLE CAS02.USER_ATTR_TYPE
	ADD CONSTRAINT  PK_USER_ATTR_TYPE PRIMARY KEY (USER_ATTR_TYPE_CD)/



CREATE TABLE CAS02.USER_ATTR_VALU
(
	USER_ID               VARCHAR2(140)  NOT NULL ,
	USER_ID_TYPE_CD       VARCHAR2(10)  NOT NULL ,
	CMPND_USER_ATTR_ID    VARCHAR2(30)  NOT NULL ,
	SMPL_USER_ATTR_ID     VARCHAR2(30)  NOT NULL ,
	USER_ATTR_INSTNC_ID   CHAR(36)  NOT NULL ,
	CRT_USER_ID           VARCHAR2(140)   DEFAULT  ' ' NOT NULL ,
	CRT_TS                TIMESTAMP   DEFAULT  SYSTIMESTAMP NOT NULL ,
	LAST_MAINT_USER_ID    VARCHAR2(140)   DEFAULT  ' ' NOT NULL ,
	LAST_MAINT_TS         TIMESTAMP   DEFAULT  SYSTIMESTAMP NOT NULL ,
	USER_ATTR_VALU_TX     VARCHAR2(255)   DEFAULT  ' ' NOT NULL 
)
	TABLESPACE CASDATA01/



CREATE UNIQUE INDEX CAS02.PK_USER_ATTR_VALU ON CAS02.USER_ATTR_VALU
(USER_ID  ASC,USER_ID_TYPE_CD  ASC,CMPND_USER_ATTR_ID  ASC,SMPL_USER_ATTR_ID  ASC,USER_ATTR_INSTNC_ID  ASC)
	TABLESPACE CASINDX01/



ALTER TABLE CAS02.USER_ATTR_VALU
	ADD CONSTRAINT  PK_USER_ATTR_VALU PRIMARY KEY (USER_ID,USER_ID_TYPE_CD,CMPND_USER_ATTR_ID,SMPL_USER_ATTR_ID,USER_ATTR_INSTNC_ID)/



CREATE INDEX CAS02.IE1_USER_ATTR_VALU ON CAS02.USER_ATTR_VALU
(CMPND_USER_ATTR_ID  ASC,SMPL_USER_ATTR_ID  ASC,USER_ATTR_VALU_TX  ASC)
	TABLESPACE CASINDX01/



CREATE TABLE CAS02.USER_ID_TYPE
(
	USER_ID_TYPE_CD       VARCHAR2(10)  NOT NULL ,
	CRT_USER_ID           VARCHAR2(140)   DEFAULT  ' ' NOT NULL ,
	CRT_TS                TIMESTAMP   DEFAULT  SYSTIMESTAMP NOT NULL ,
	LAST_MAINT_USER_ID    VARCHAR2(140)   DEFAULT  ' ' NOT NULL ,
	LAST_MAINT_TS         TIMESTAMP   DEFAULT  SYSTIMESTAMP NOT NULL ,
	USER_ID_TYPE_NM       VARCHAR2(60)   DEFAULT  ' ' NOT NULL ,
	USER_ID_TYPE_DN       VARCHAR2(255)   DEFAULT  ' ' NOT NULL 
)
	TABLESPACE CASDATA01/



CREATE UNIQUE INDEX CAS02.PK_USER_ID_TYPE ON CAS02.USER_ID_TYPE
(USER_ID_TYPE_CD  ASC)
	TABLESPACE CASINDX01/



ALTER TABLE CAS02.USER_ID_TYPE
	ADD CONSTRAINT  PK_USER_ID_TYPE PRIMARY KEY (USER_ID_TYPE_CD)/


