--******************************************************
--CONSTANT
--***************************************************

update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '0'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('bannerPage');

update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = 'COLLoginUser'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('action');

update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = 'CO'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('c_bus_id');

update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = 'A00001'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('c_site_id');

update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '12345'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('c_user_ident');

update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = 'http://malta.bbndirht.external.hp.com/portal/site/smartportal'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('home_url');

update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = 'P101'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('v_ggss');

update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = 'ppro'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('user_aaid');

update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = 'SDLFGHIOE43098EFG89340340UJLG5'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('site_qual');

update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = 'ppro_emea'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('aaid');

update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '3'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('partner');


--***************************************************
-- USERGroups
--***************************************************
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${UserGroups}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('UserGroups');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${spp:inGroup(''LOCAL_SECURITY_LitwebWithOrderCapabilities'',UserGroups)}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('LitwebOrderFlag');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${spp:inGroup(''LOCAL_SECURITY_LitwebWithOrderCapabilities'',UserGroups)}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('c_order_flag');

--***************************************************
--FROM  USERCONTEXT
--***************************************************
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${Programs}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('Programs');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${Accreditations}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('Accreditations');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${PartnerTypes}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('PartnerTypes');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${PartnerSubTypes}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('PartnerSubTypes');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${BlnPhaseIn}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('BlnPhaseIn');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${BlnPhaseOut}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('BlnPhaseOut');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${IsHybrid}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('IsHybrid');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${CBN}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('CBN');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${PortalSessionId}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('PortalSessionId');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${PreferredLanguageCode}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('LanguageCode');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${PartnerLegalName}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('PartnerLegalNameHQ'); 
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${PartnerProId}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('PartnerId'); 
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${title}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('Salutation'); 
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${PartnerPhone}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('User_WorkPhone');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${PhysAdLine1}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('addr_1');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${PhysAdLine2}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('addr_2');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${PhysAdLine3}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('addr_3');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${PartnerLegalName}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('bus_entity_name');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${PhysCity}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('city_name');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${FirstName}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('contact_contact_first_name');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${LastName}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('contact_contact_last_name');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${CountryCode}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('country_code');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${Email}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('email');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${PartnerFax}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('fax');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${PhysPostalCode}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('postal_code');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${username}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('web_user_login_id');

update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${HPPUserId}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('ReferrerPortalID');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${PhysAdLine1}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('street');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${PhysPostalCode}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('zipcode');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${PhysCity}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('city');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${CountryCode}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('country');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${PartnerPhone}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('phone');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${PartnerName}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('company');



--Standard Parameters
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${CountryCode}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('CountryCode');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${HPOrg}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('HPOrg');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${HPPUserId}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('HPPUserId');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${HpInternalUser}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('HpInternalUser');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${JobFunction}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('JobFunction');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${PartnerLegalName}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('PartnerLegalName');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${PartnerName}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('PartnerName');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${PartnerNameHQ}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('PartnerNameHQ');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${PartnerProId}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('PartnerProId');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${PartnerProIdHQ}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('PartnerProIdHQ');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${PhysCountry}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('PhysCountry');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${PortalSessionId}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('PortalSessionId');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${PreferredLanguageCode}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('PreferredLanguageCode');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${UserFax}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('UserFax');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${UserPhone}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('UserPhone');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${title}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('title');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${Tier}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('Tier');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${IsPartnerAdmin}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('IsPartnerAdmin');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${LastName}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('LastName');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${LastLoginDate}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('LastLoginDate');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${FirstName}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('FirstName');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${PhysPostalCode}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('PhysPostalCode');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${PrimaryChannelSegment}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('PrimaryChannelSegment');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${PartnerPhone}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('PartnerPhone');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${PartnerFax}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('PartnerFax');

update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${PhysCity}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('PhysCity');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${PhysAdLine1}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('PhysAdLine1');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${PhysAdLine2}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('PhysAdLine2');
update SPP_ESERVICE_PARAMETER set SPP_ESERVICE_PARAMETER.EXPRESSION = '${PhysAdLine3}'
where UPPER(SPP_ESERVICE_PARAMETER.EXPRESSION) = UPPER('PhysAdLine3');

update spp_eservice_parameter set expression = '${HPPUserId}' 
where expression = '${web_user_login_id}'

