---------------
--Producer DB--
---------------
CREATE TABLE PRODUCER (
	STATUS NUMBER(1), 
	PRODUCERKEY VARCHAR2(256) PRIMARY KEY, 
	NAMESPACE VARCHAR2(256), 
	INSTANCENAME VARCHAR2(256), 
	REQUIRESREGISTRATION NUMBER(1), 
	SUPPORTSINBANDREGISTRATION NUMBER(1),
	VERSION VARCHAR2(10),
	OFFEREDPORTLETS VARCHAR2(1024), 
	PRODUCERPROFILEMAP VARCHAR2(256), 
	REGISTRATIONPROPERTIES VARCHAR2(256), 
	REGISTRATIONVALIDATORCLASSNAME VARCHAR2(256), 
	PORTALID VARCHAR2(256) 
); 

CREATE TABLE CONSUMER_REGISTRATION ( 
	STATUS NUMBER(1), 
	CONSUMERNAME VARCHAR2(256) , 
	REGISTRATIONHANDLE VARCHAR2(256) PRIMARY KEY, 
	CONSUMERAGENT VARCHAR2(256), 
	METHODGETSUPPORTED NUMBER(1), 
	CONSUMERMODES VARCHAR2(256), 
	CONSUMERWINDOWSTATES VARCHAR2(256), 
	CONSUMERUSERSCOPES VARCHAR2(256), 
	CUSTOMUSERPROFILEDATA VARCHAR2(256), 
	REGISTRATIONPROPERTIES VARCHAR2(256),
	LIFETIMETERMINATIONTIME VARCHAR2(256),	
	PRODUCERKEY VARCHAR2(256)
); 

CREATE TABLE REGISTRATION_PROPERTY (
	PRODUCERKEY VARCHAR2(256), 
	LABELRESOURCENAME VARCHAR2(256), 
	LABELVALUE VARCHAR2(256), 
	LABELLANG VARCHAR2(256), 
	HINTRESOURCENAME VARCHAR2(256), 
	HINTVALUE VARCHAR2(256), 
	HINTLANG VARCHAR2(256), 
	NAME VARCHAR2(256) PRIMARY KEY, 
	TYPE VARCHAR2(256), 
	EXTENSION VARCHAR2(256)
);

CREATE TABLE PRODUCER_GLOBAL_PROFILE_MAP (

	PORTALID VARCHAR2(256) NOT NULL,
	PORTLETATTR VARCHAR2(256) NOT NULL,
	WSRPATTR VARCHAR2(256) NOT NULL,
	CONSTRAINT PROD_GLOBAL_PROFILE_PK PRIMARY KEY (PORTALID, PORTLETATTR)
);


CREATE TABLE PRODUCER_GLOBAL_DATA ( 

    PORTALID VARCHAR(256) NOT NULL, 
    PRODUCERDISABLE NUMBER(1) NOT NULL, 
    CONSTRAINT PRODUCER_GLOBAL_DATA_PK PRIMARY KEY (PORTALID) 
);


---------------
--Consumer DB--
---------------
CREATE TABLE CONFIGURED_PRODUCERS ( 
	PORTAL_ID VARCHAR2(256) NOT NULL, 
	CONFIGURED_PRODUCER_ID VARCHAR2(256) NOT NULL, 
	CONFIGURED_PRODUCER_NAME VARCHAR2(256) NOT NULL, 
	NAMESPACE VARCHAR2(256), 
	PRODUCER_URL VARCHAR2(256) NOT NULL,
	PRODUCER_VERSION VARCHAR2(10) NOT NULL,
	PRODUCER_MARKUP_ENDPOINT VARCHAR2(256) NOT NULL, 
	PRODUCER_STATUS SMALLINT, 
	REGISTRATION_DATA VARCHAR2(4000), 
	REGISTRATION_CONTEXT VARCHAR2(4000), 
	SERVICE_DESCRIPTION CLOB, 
	USER_CATEGORY_MAPPING CLOB, 
	CUSTOM_USER_PROFILE CLOB, 
	SD_LASTMODIFIED NUMBER(20), 
	IDENTITY_PROPAGATION_TYPE VARCHAR2(256), 
	ENTITY_VERSION NUMBER(5), 
	CONSTRAINT CONFIG_PRODUCERS_PK PRIMARY KEY (PORTAL_ID, CONFIGURED_PRODUCER_ID)
); 

CREATE TABLE CONSUMER_GLOBAL_DATA ( 
	PORTAL_ID VARCHAR2(256) PRIMARY KEY, 
	CONSUMER_ENABLE NUMBER(1) NOT NULL, 
	DEFAULT_REGIS_DATA VARCHAR2(4000)
); 

CREATE TABLE CONSUMER_NAME ( 
	PORTAL_ID VARCHAR(256) NOT NULL, 
	NAMESPACE VARCHAR(256) NOT NULL, 
	CONSUMER_NAME VARCHAR(256) NOT NULL, 
	CONSTRAINT CONSUMER_NAME_PK PRIMARY KEY (PORTAL_ID, NAMESPACE) 
); 

CREATE TABLE CONSUMER_DEF_USER_PROFILE_MAP ( 
	PORTAL_ID VARCHAR2(256) NOT NULL, 
	PROFILE_KEY VARCHAR2(256) NOT NULL, 
	PROFILE_VALUE VARCHAR2(256) NOT NULL, 
	CONSTRAINT CONS_USER_PROFILE_PK PRIMARY KEY (PORTAL_ID, PROFILE_KEY) 
); 


