// This file just demonstrates how you can reference JavaScript from
// your HTML Viewer portlet view file.  Currently it is not used.  See 
// the html_viewer.html file for more information.

document.writeln();
document.writeln('<p>This content was generated by external JavaScript.</p>');
document.writeln();

// End of file